### ISSUE TITLE
migrate things from chipper that should always be on master

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#1]
From 9/29/15 dev meeting...

Take a closer look at what should be moved over from chipper.

checkoutShas.js was copied from chipper, then modified.  One of these should be deleted or renamed.

**Comment by aaronsamuel137** [comment]
While looking at https://github.com/phetsims/chipper/issues/345, I saw that build-server depends on getDeployConfig from chipper. In light of this, it would probably be advisable to move it over to perennial too.

Do you see any downsides to this @pixelzoom?

**Comment by pixelzoom** [comment]
@aaronsamuel137 getDeployConfig.js is used by `deploy-dev` and `deploy-production tasks`.  I haven't used those tasks yet, and I'm not very familiar with their implementation.  So I can't answer your question with confidence.  That said... If getDeployConfig.js is moved to perennial, and perennial is design to be always on master, then it's possible that older versions of those 2 grunt tasks might get broken unless backward compatibility is maintained in getDeployConfig.js.  That probably means that new config information can be added, but config info shouldn't be removed (but can be marked `@deprecated`).

**Comment by jonathanolson** [comment]
Discussing what type of things should move would be valuable.

Pros of moving to perennial:

- When old versions of sims are checked out, you still have the latest copy (very backwards-compatible, but sim builds can't rely on it)
- Chipper's node_modules could shrink, which will speed up builds and potentially checking out node_modules over time.
- Can update things here that apply to release branches without having to have an automated maintenance release (say we need to change how sims get deployed)

Cons of moving to perennial:

- Currently aren't able to run perennial commands from sim directories. This is possible, but wouldn't work for older sim release branches without a maintenance release on them.

So some things seem pretty obvious to move to perennial:

- sort-require-statements and insert-require-statements. You don't want your IDE integration to break when you check out older sims.

Other things probably should move over, but I'd like to confirm:
- find-duplicates/commits-since/report-third-party/report-media/checkout-shas/checkout-master/create-sim/update-copyright-dates
- almost everything under chipper/bin and chipper/data

Do we ever need to run any of those on a non-master branch? Objections?

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> Do we ever need to run any of those on a non-master branch? Objections?

We need to run `checkout-master` on a non-master branch. `print-shas.sh` is sometimes useful while working on a release branch and its dependencies, but could live without it.

No objections.

**Comment by samreid** [comment]
I'm unclear on what belongs in perennial vs chipper.  It seems that whatever moves to perennial locks us in to a particular way of doing it.  For instance, let's say we move "find-duplicates" to perennial.  Seems safe enough, but then what if we rename "js" directories to "src" one day (this will not happen but I am speaking hypothetically), then we would have to change the way find-duplicates works in perennial and hence it would (a) fail on old code or (b) need logic that supports both styles.

**Comment by jonathanolson** [comment]
> then we would have to change the way find-duplicates works in perennial and hence it would (a) fail on old code

Yes, if we would want something to be version-specific so that we can check out an old version of it, then it should not be in perennial.

**Comment by zepumph** [comment]
>sort-require-statements and insert-require-statements. You don't want your IDE integration to break when you check out older sims.

I agree that those should be on master always, but perennial doesn't seem like the right repo for that. I always thought of perennial as a repo that was for the build-server. What if we made another repo that is "always on master" that holds development tools

@samreid 
> It seems that whatever moves to perennial locks us in to a particular way of doing it.

Or at least locks us to a script that handles backwards compatibility.

**Comment by jonathanolson** [comment]
> What if we made another repo that is "always on master" that holds development tools

That is almost by definition what perennial is supposed to be. Its GitHub documentation says:

> Maintenance tools that won't change with different versions of chipper checked out 

It just turns out we also decided that the build-server code can share maintenance code with other things (and stays on master), so it can live on perennial.

**Comment by pixelzoom** [comment]
12/4/17 dev meeting:  OK to move chipper/data/ files over.  Will revisit at next dev meeting if needed.

**Comment by pixelzoom** [comment]
Following chipper 2.0 merge, I suspect that this can be closed. But @mattpen and @jonathanolson would need to confirm.

**Comment by jonathanolson** [comment]
Closing. @mattpen can reopen if there's something I missed.
