### ISSUE TITLE
Should we change how dev deploys work?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#104]
Right now they require an up-to-date checked-in master version of the sim (so that it can commit the version, not have conflicts, and also commit the top-level dependencies.json).

This seems like it has been inconvenient for developers. Additionally I really don't care about the top-level dependencies.json (I've never used it).

The one main reason I see that we're still doing this is so that we don't have what the "latest dev version" is spread across multiple sim branches. In the past, if you could branch and dev deploy, it was easy to deploy conflicting versions (e.g. 1.0.0-dev.8) from different branches, and it wasn't clear that it was from a branch.

So are there any alternative solutions I should explore for handling how things work now? (Storing sim versions in an alternate repo would get around this type of thing, but I'm not sure it's worth it).

Tagging for dev meeting for thoughts.

**Comment by zepumph** [comment]
>The one main reason I see that we're still doing this is so that we don't have what the "latest dev version" is spread across multiple sim branches. In the past, if you could branch and dev deploy, it was easy to deploy conflicting versions (e.g. 1.0.0-dev.8) from different branches, and it wasn't clear that it was from a branch.

Part of me thinks that they are dev versions, and should be thought of inconsequentially. They are supposed to be snapshots taken of a sim for a specific purpose at that time. They aren't meant to have any temporal value. I think it is more up to the developer to document a specific dev release link in the issue that called for it. Also if this is a problem then maybe we should be more strict about requiring an issue number in the dependencies "message" for dev releases that are out of the ordinary (i.e. on a different branch or something). That way it is easier to get from phet-dev back to an explanation about what that dev version if all about.

Especially because of work that is often done in the same repo regarding a11y, phet-io, and sim features, a newer dev version could be different any number of ways from the last.

**Comment by jonathanolson** [comment]
> They are supposed to be snapshots taken of a sim for a specific purpose at that time.

So call me crazy, but what if instead of `dev.8` it was `dev.{{TIMESTAMP}}`, OR some type of version that is not incremented but the deployment process figures out the directory.

**Comment by jessegreenberg** [comment]
The current process has not been inconvenient for me. If I need to deploy a dev version that is not out of master, one-off deploys/branches have served nicely and the purpose of deploy has been documented in the branch issue.

**Comment by samreid** [comment]
I'd like to hear more about what the specific problems have been.  The existing process has been clear and straightforward for my development.

**Comment by zepumph** [comment]
There has been one time for interaction-dashboard that I really wanted to create a dev version from a branch, because it didn't feel formal enough for a one off branch, but in retrospect I think that it probably belonged as a one off branch to support a permanent link for a paper. See https://github.com/phetsims/interaction-dashboard/issues/81

I can understand (though I have not yet needed to do it) the argument for publishing a dev version from an rc branch just to make sure that all changes are good before continuing with the RC (I may be in the minority here).

Honestly as I write this I may be talking myself out of this decision. Not sure. I'm excited to talk about it more tomorrow!

**Comment by jonathanolson** [comment]
Current process seems fine.
