### ISSUE TITLE
Should RC deploys be required between production deploys?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#105]
It was decided that it was OK to assume this was correct, but in practice it's definitely not been what has been desired multiple times. We've run into "quick deploys" multiple times now where I've had to advise people to "force and RC deploy" or to just patch package.json so the auto-increment will work.

Can we get rid of this restriction?

And how to we handle version auto-incrementing if you do a production deploy, as then there would be two modes:

1. The current behavior is to assume the last production deploy may not have fully succeeded. We've had a sizable number of failed builds on the build-server, so it's important to be able to re-send production deploys.
2. The alternative behavior would presumably be to increment the maintenance version and do another production deploy.

Any thoughts for how to handle this? Tagging for dev meeting.

**Comment by pixelzoom** [comment]
This restriction was most recently encountered in https://github.com/phetsims/molarity/issues/48.  We were going to patch PhET-iO issue after multiple confirmations in local builds.  But we discovered that an RC is required between production deploys.  I could have published an RC, ignored it, then published the production version.  But that ignores the "process" problem rather than addressing it -- it makes no sense to publish a RC if there's no intent to qualify that RC through the QA process.  I would be fine with keeping things "as is" if we requiring all maintenance releases to go through the RC process, and therefore require at least one RC prior to each production deploy.

**Comment by zepumph** [comment]
To try to balance the potential need for both items in @jonathanolson's list, perhaps we could have an option like `noRC` that "forces" the production build without an RC. This option is only used manually, and not automatically be the build server, so there would be a differentiation between uses, and failed builds that occurred with the `noRC` option could be handled right then. 

I also think this would be a nice solution since I think the general "process" is that we want RC testing done for production builds, even if they are just spot checks. It should be a thoughtful and deliberate choice to bypass said testing and go straight to a maintenance release (i.e. with an option).

**Comment by jessegreenberg** [comment]
I have been asked to publish maintenance releases where the only change is to update credits and in these cases testing seems excessive.

I like @zepumph's suggestion in https://github.com/phetsims/perennial/issues/105#issuecomment-413384329.

**Comment by samreid** [comment]
> I have been asked to publish maintenance releases where the only change is to update credits and in these cases testing seems excessive.

Since we have no easy way to diff published simulations, a step where there is at least a spot check before publication sounds valuable.  If it is intended to be an incremental change in SHAs, it doesn't need to be a full test matrix.

Can someone identify the disadvantage of creating an RC, even if it is only spot tested?  Does it take too long or complicate the process?

**Comment by pixelzoom** [comment]
8/23/18 dev meeting consensus:  Continue to require an RC before a production version.  If it's something simple, test the RC yourself without involving QA, then deploy production.  So no changes to build process.
