### ISSUE TITLE
Maintenance release for new ios specific image

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#119]
In phetsims/phet-ios-app#425, we added an ios optimized thumbnail.  In order for this to be accessible, a maintenance release will be needed.

@jonathanolson - Has the MR documentation been improved since we released the twitter card changes? If so, I'm game to give this a shot on my own.  If not, I'd like to schedule this in a time where you could provide guidance.

This won't be needed until we release v1.3 of the ios app, so it isn't urgent at this time.

**Comment by jonathanolson** [comment]
This should be noted maybe in https://github.com/phetsims/perennial/issues/110, since @zepumph and I may be doing a maintenance release first (not sure about the schedule). Documentation is in https://github.com/phetsims/perennial/blob/master/doc/automated-maintenance-process.md now. Does that look sufficient for documentation? (I don't recall how it was for the twitter-card one, but that file may not have existed).

**Comment by mattpen** [comment]
This is not quite ready as we'll probably also be adding an xz compressed version of the _all.html file before we release this.

**Comment by mattpen** [comment]
The documentation looks much better, thanks @jonathanolson.  I'm willing to give this a shot on my own once it is ready.

**Comment by mattpen** [comment]
This approach was abandoned to to image quality concerns.
