### ISSUE TITLE
build server should remove old versions when publishing new ones

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#16]
We are running into some issues with the buildup of historical versions of the simulations and their translations, see https://github.com/phetsims/installer-builder/issues/10.  During the 3/17/2016 developer meeting it was decided that we don't need to keep these old versions around, since we will have them on spot or its replacement anyway.  There is an issue to remove them from the web server itself, see https://github.com/phetsims/website/issues/408, but the build server will also need to be modified to remove old versions each time new ones are deployed.

**Comment by jonathanolson** [comment]
If we're removing old versions, how are we going to support phet-io playback (or other playback) in general?

Should we discuss again?

**Comment by samreid** [comment]
For PhET-iO versions, we have a current plan and a proposed plan:

Current Plan: every PhET-iO version must remain available on the phet-io website.  This is because we had no way to protect against breaking changes.

Proposed Plan: every latest PhET-iO {{MAJOR}}.{{MINOR}} version must remain available on the phet-io website.  This is because our proposed stability plan breaks compatibility when minor or major version increments.

**Comment by mattpen** [comment]
Additional discussion in https://github.com/phetsims/website/issues/408

**Comment by ariel-phet** [comment]
It seems like leaving the old versions up on the production server is not a problem so long as it is not affecting the installer build or causing server load/etc issues by being crawled/indexed by google. Those questions will be dealt with by @mattpen. Closing.
