### ISSUE TITLE
Committed strings in babel aren't being published to the website

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/perennial#178]
Two translators have reported fully translating Build an Atom (Portuguese _pt and Telugu _te) -- however, this may not be isolated to BaM. The strings appear to have been correctly [committed to babel](https://github.com/phetsims/babel/tree/master/build-an-atom), but [aren't being published to the site](https://phet.colorado.edu/en/simulation/build-an-atom).

**Comment by jbphet** [comment]
The root cause was that the code for the deployImages task was never resolving, so the task queue was getting stopped up.  Should be fixed now.  We tested deployImages and a translation build (the ab version of Chains) and both worked.

I'll see if I can create a script to build the translations that didn't get deployed while the build server was out of commission.

**Comment by jbphet** [comment]
Due to this problem, the build server has not been operating since May 21.  I just checked the logs, and it looks like there are 19 requests for translation builds that did not get executed between then and now.  With roughly 2-3 hours of additional effort, I think I could create a NodeJS script that will allow me (and others in the future) to trigger the build server to build and deploy the missing translations.  The alternative to this would be to extract the list of missed builds from the logs and give it to @oliver-phet and have him let the translators know that they need to resubmit.

@ariel-phet - What are your thoughts on this?  The script would be useful if and when situations like this come up in the future, but there are a lot of other priorities these days.

**Comment by jbphet** [comment]
Here are the log entries that indicate which translations haven't been deployed.  Some are actually redundant, so it's not actually 19 unique redeploys.  More like 15.

```
rosetta[30929]: 2020-05-28 08:08:13 | info - build requested for sim = diffusion, locale = fi
rosetta[30929]: 2020-05-28 08:25:40 | info - build requested for sim = energy-forms-and-changes, locale = fi
rosetta[30929]: 2020-05-28 13:15:36 | info - build requested for sim = gas-properties, locale = es
rosetta[30929]: 2020-05-28 16:11:08 | info - build requested for sim = build-an-atom, locale = pt
rosetta[30929]: 2020-05-29 05:43:29 | info - build requested for sim = balloons-and-static-electricity, locale = mr
rosetta[30929]: 2020-05-29 09:52:03 | info - build requested for sim = ohms-law, locale = es_PE
rosetta[74617]: 2020-06-05 04:08:28 | info - build requested for sim = color-vision, locale = ca
rosetta[74617]: 2020-06-07 09:51:23 | info - build requested for sim = charges-and-fields, locale = kn
rosetta[74617]: 2020-06-09 06:11:32 | info - build requested for sim = waves-intro, locale = cy
rosetta[147346]: 2020-06-09 16:06:13 | info - build requested for sim = build-an-atom, locale = pt
rosetta[147346]: 2020-06-09 23:31:19 | info - build requested for sim = circuit-construction-kit-dc, locale = mr
rosetta[147346]: 2020-06-09 23:41:05 | info - build requested for sim = ohms-law, locale = mr
rosetta[147346]: 2020-06-09 23:44:44 | info - build requested for sim = resistance-in-a-wire, locale = mr
rosetta[147346]: 2020-06-10 01:17:33 | info - build requested for sim = build-an-atom, locale = pt
rosetta[147346]: 2020-06-10 01:28:44 | info - build requested for sim = build-an-atom, locale = pt
rosetta[147346]: 2020-06-10 05:19:22 | info - build requested for sim = waves-intro, locale = cy
rosetta[147346]: 2020-06-10 10:04:50 | info - build requested for sim = build-an-atom, locale = pt
rosetta[147346]: 2020-06-10 13:05:12 | info - build requested for sim = build-an-atom, locale = te
rosetta[147346]: 2020-06-10 18:29:49 | info - build requested for sim = circuit-construction-kit-dc, locale = mr
```

**Comment by ariel-phet** [comment]
@jbphet I actually think given the COVID situation and our worldwide support, it is reasonable to address as a priority.

**Comment by jbphet** [comment]
I've now published the translations that didn't go out while the build-server was out of commission.  I didn't verify every one, but I spot checked several and they looked correct

@oliver-phet - can you notify any translators who might be interested, and particularly those that contacted us, that their translations should be up now?  Thanks.

**Comment by oliver-phet** [comment]
Translators notified, closing.
