### ISSUE TITLE
Add Prototype Publication Process 

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#190]
In response to the high demand for remote learning due to covid-19, we started publishing simulation prototypes.  These are versions of a simulation where https://phet.colorado.edu/sims/html/{{sim-name}}/latest/{{sim-name}}_en.html exists prior to the publication of 1.0.0.  Eventually, the file is replaced by the normal production deploy process.

Here is the current process:

1. Deploy an RC or Dev version to phet-dev.colorado.edu.
2. Create this directory on phet-server: `/data/web/static/phetsims/sims/html/{{sim-name}}/latest`
3. Copy the english file for the target version to this directory.
4. Remove phet from the filename
5. Ensure that the file is owned by `tomcat:phet` and has group read/write permissions.
6. Open an issue in the simulations repo with a `blocks-sim-publication` label asking the responsible dev to remove this file before deploying version 1.0.0.

<hr/>

Some options for improving the process.  Some of these are not good ideas.

1. Just deploy production versions but do not publish them.
    - No additional development needed, other than documenting this process somehow.
    - One potential problem is that the first version actually published is 1.0.N, where N is not 0.
2. Add a flag to the RC deployment process. This flag will tell the build-server to copy the directory to both the production location and phet-dev.
    - Modifying the RC process will have a development cost.  
    - I'll also need to ensure that production deploy of 1.0.0 doesn't unexpectedly fail due to a pre-existing directory. 
    - It would take additional development time to also modify the dev deploy process or we would have to require that prototypes are an RC version.
3. Somehow modify the one-off deployment process to allow phet-server as a target
    - I don't have any good ideas here, but maybe it is worth discussion.
4. Leave the current process in place.
   - We know it works.
   - Requires documentation, manual work by multiple parties, relies on tribal knowledge. 
5. ???

**Comment by samreid** [comment]
Another option: 

(6) Think of the "prototype" as 1.0.0, name it as such and use our normal deploy process.  Can we set up the links like we want without making the sim pages visible?

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

**Discussion:**

@mattpen: Easiest method would be publishing to production but not making it visible, with the drawback that the versioning will be off (see Method 1 in the [OP](https://github.com/phetsims/perennial/issues/190#issue-653738061))

@ariel-phet: I'm concerned about managing the history of these production builds. We should have a clear understanding that this version is a 'prototype' without a typical RC history.

@mattpen: We can toggle a flag for prototype visibility.

@ariel-phet @Denz1994: We will continue with these prototypes versions even after Covid-19 calms down, so we should add this in our processes.

@samreid: This should be treated as an RC with a test matrix and stable SHAs. @pixelzoom This wasn't the case for Natural Selection.

@zepumph: Copy production to a new place on phet-server (where only prototypes live) with similar build process code to support this.

@pixelzoom @mattpen: It would be difficult to have a prototype of a sim that is already published because they would share the same link.  They would have to be in different places on phet-server

@ariel-phet: In the short-term, we can assume prototypes are not sims that are already published.

@pixelzoom: Prototype links can be redirected to the latest publication, so old prototype links don't get bookmarked and reused after publication.

@mattpen @samreid: This will require changes in several places and require maintenance for these new prototype sims.

@jbphet @samreid: We follow through with the publication process without making it visible on the website. Keep an issue open that tracks the test cycle for this prototype. @ariel-phet Agrees because we would be using an already established process.

@pixelzoom @ariel-phet @jbphet : Introducing QA into the prototype build process will involve:
- New test matrix template that isn't 
- Label for the issue
- QA issue assigned for relevant party (designer, one QA member, etc.)

**Resolution:**
@ariel-phet will communicate with QA to develop steps for a new test cycle for a prototype. Natural-Selection may be the next candidate for this process.

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

**Resolution:**
@ariel-phet will communicate with QA to develop steps for a new test cycle for a prototype. Natural-Selection may be the next candidate for this process.

@jbphet mentioned this should be documented in the chipper 2.0 md documents. @ariel-phet will take a first stab at this.

**Comment by pixelzoom** [comment]
Natural Selection is ready for prototype publications, see https://github.com/phetsims/natural-selection/issues/116#issuecomment-665242012.   I'll be happy to beta test the process documentation in [chipper-2.0.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md) when it's ready.

**Comment by pixelzoom** [comment]
@ariel-phet When you've completed a draft of the process description in chipper-2.0.md, let's have @mattpen review it before I proceed with  phetsims/natural-selection#116. I'm not at all familiar with the website end of this process.

**Comment by ariel-phet** [comment]
@pixelzoom @mattpen Prototype process documentation has been given a rough draft in https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md (near the bottom).

**Comment by mattpen** [comment]
This process looks fine as far as I am concerned.  ✓

**Comment by KatieWoe** [comment]
Issue template for prototype tests has been made: https://github.com/phetsims/QA/blob/master/issue-templates/prototype-test-template.md. There is also a testing matrix template.

**Comment by pixelzoom** [comment]
I made a couple of edits to the process description and QA template, but overall looks good.  I followed the process to create natural-selection 1.0.0-rc.1, see https://github.com/phetsims/QA/issues/522.

Back to @ariel-phet.  If there's nothing else to do here, please close.
