### ISSUE TITLE
disable the git pre-commit hooks for non-sim related or non-javascript repos

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#208]
From slack, @mattpen said:

> Is there some way to disable the git pre-commit hooks for non-sim related or non-javascript repos?  I don’t think commits to phet-android-app, for example, need to run lint or qunit tests.

**Comment by samreid** [comment]
I ran `node ../perennial/js/scripts/hook-pre-commit.js` from phet-android-app and saw an error during the report-media task.  So I added a way to opt certain repos out of reportMedia.  The other way to go about this would be to prevent the precommit hooks from populating in those repos in the first place, but maybe hook-pre-commit.js makes sense as a central point (in case we do decide to add some precommit actions to phet-android-app in the future.

**Comment by samreid** [comment]
`assert` is failing precommit hooks because `getPhetLibs.js` requires package.json to have a `phet:{phetLibs:[]}` entry.  This code makes `getPhetLibs` more graceful, and the precommit hooks pass.  But I am wondering if we should just require all package.json to have a `phet:{phetLibs:[]}` entry.  @zepumph can you please advise?

**Comment by samreid** [comment]
Also, I iterated through all active repos like so `for-each.sh active-repos node ../perennial/js/scripts/hook-pre-commit.js` and found problems in many repos.  I'll look at opting them out.  Regarding the above comment, I don't think we should require "phet" and "phetLibs" entries for all repos, so I'll factor out the graceful handling to `getPhetLibs.js`

**Comment by samreid** [comment]
In the commits, I opted out of certain tests for certain repos, and added graceful handling for missing entries in package.json.   After the commits, all repos are passing the precommit hooks.  @zepumph can you please review, particularly about the change to getPhetLibs.js?

**Comment by zepumph** [comment]
I'm bummed about duplication of opt out lists.

https://github.com/phetsims/chipper/blob/ba14aa5aa70c4166a471569cd35d1da89a56fd28/eslint/.eslintignore#

https://github.com/phetsims/chipper/blob/60ccd7596ac8c4e1f2d5dc91736f1be17923a363/js/grunt/lint.js#L18-L32

I could not figure out a way to combine the two above lists. Could we work to combine `optOutOfLint` with the list in `lint.js` so that there is only one list for that?


I see that you start this line like so: `packageObject &&`, but you don't actually support gracefully a lack of `package.json`. For example, if you run in babel after removing babel from the report media opt out, it will fail because there is no package.json. If you want to support a graceful getPhetLibs such that it doesn't even need package.json, I feel like more will need to be done, but I'm not sure that we should support that. I agree that you shouldn't have to specify phetLibs for getPhetLibs to work.

**Comment by samreid** [comment]
> I could not figure out a way to combine the two above lists.

Would it work for lint.js to read in .eslintignore and parse it to create its array?

> Could we work to combine optOutOfLint with the list in lint.js so that there is only one list for that?

Sounds reasonable, but would it be even better to just have `grunt lint` be a no-op for those repos?

**Comment by zepumph** [comment]
> Sounds reasonable, but would it be even better to just have grunt lint be a no-op for those repos?

Yes. Everything you said above would be better than what is currently there, but I have not been able to get it to work. I'd love it if you wanted to take a try. Also if you just close this and we go with two list copies, I understand. Especially since one is in perennial and one in chipper (so annoying).

**Comment by samreid** [comment]
I moved the remaining part to https://github.com/phetsims/perennial/issues/212 and proposed a solution for it.  Closing.
