### ISSUE TITLE
Build server failure: Build aborted,at least one repository failed to pull master

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#221]
I am ready to production deploy Ratio and Proportion, but there was an error with the build server:

```
error: Build failure: Build aborted,at least one repository failed to pull master. Sim = ratio-and-proportion Version = 1.0.0 Brands = phet Locales = * Shas = {"comment":"# ratio-and-proportion 1.0.0 Wed Mar 24 2021 18:10:28 GMT-0800 (Alaska Daylight Time)","assert":{"sha":"3df8c5ff9a465b031f84195a90bbb7e1be10a14d","branch":"HEAD"},"axon":
. . . . 
```

When pulling all, some repos had errors like:

```
Mar 24 20:11:26 phet-server.int.colorado.edu build-server[28967]: debug: stderr: fatal: could not read Username for 'https://github.com': No such device or address

```

I feel a bit stuck, though @samreid had some great ideas about how to fix this like 
https://github.com/github/hub/issues/1644 and https://github.com/kemayo/sublime-text-git/issues/176#issuecomment-9606079

I think it makes the most sense to wait for @mattpen to get back to see what is up. Assigning to him.

**Comment by pixelzoom** [comment]
Since we established that this is a general problem, I've transferred this issue from ratio-and-proportion to perennial.

**Comment by pixelzoom** [comment]
Slack:

Google Calendar shows that Matt is out through the end of the week.  Is anyone else available to look into https://github.com/phetsims/perennial/issues/221?  If it’s not fixed today or tomorrow, that’s going to throw a monkey wrench into my plans to take some time off next week, and ability to meet Ido’s deadline.

Sam Reid  2:19 PM
@jonathanolson said “I’ll be able to check into it”

**Comment by pixelzoom** [comment]
Slack:

Michael Kauzmann  3:03 PM
Unlike for ratio and proportion, I see no way to work around this for molecule polarity because it needs PhET-iO repos (which require passwords I guess).

**Comment by jonathanolson** [comment]
Had issues pulling number-play and rosetta due to probable history changes (was faster to reclone). Also had to provide authentication for GitHub. I couldn't get an authentication token quickly for the phet-dev user, so I used the password provided and set it up with the credential helper.

Bumper deploy completed with no errors, so this shouldn't block anymore. @mattpen should look into this more once he's back.

**Comment by pixelzoom** [comment]
Thanks for the quick attention to this issue @jonathanolson.  I was able to deploy Molecule Polarity 1.1.0-rc.2.

**Comment by zepumph** [comment]
@jonathanolson can you please specify a bit more detail on how you fixed the issue (in the off chance that I could do it next time?)

**Comment by jonathanolson** [comment]
I saw error messages stating that pulls had failed. Looked up build-server docs, saw that things lived in data/share/phet/phet-repos, ran:

```sh
phet-admin@phet-server:/data/share/phet/phet-repos$ perennial/bin/status.sh
```

saw
```
number-play                              master behind 19
 M .gitignore
 M images/apple_png.js
 M images/ball_png.js
 M images/compare_screen_icon_png.js
 M images/compare_screen_placeholder_png.js
 M images/dog_png.js
 M images/game_screen_icon_png.js
 M images/game_screen_placeholder_png.js
rosetta                                  master behind 98
 M .gitignore
 M README.md
 M css/main.css
 D dev/.psql_history
 D dev/Dockerfile
 D dev/docker.env
 D dev/start_pg_docker.sh
 M doc/admin-guide.md
 M doc/how-to-change-a-string-key.md
 M doc/implementation-notes.md
 D img/rosetta.jpg
?? doc/running-locally.md
?? doc/running-remotely.md
```

with pulls failed, classic symptoms of some history-changing commit where if the build-server pulls at a certain time, then future pulls will fail out.

Recloned:
```sh
phet-admin@phet-server:/data/share/phet/phet-repos$ rm -Rf rosetta
phet-admin@phet-server:/data/share/phet/phet-repos$ rm -Rf number-play/
phet-admin@phet-server:/data/share/phet/phet-repos$ perennial/bin/clone-missing-repos.sh 
```

Did a pull-all, but it asked for a username/password for interaction-dashboard (the first private repo). Went to the credential doc, tried the token for the phet-dev account:
```sh
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git pull
Username for 'https://github.com': phet-dev
Password for 'https://phet-dev@github.com': 
remote: Invalid username or password.
```

GitHub required some extra security for getting an authentication token, so since that wouldn't work right then I decided to use the phet-dev account's password (with the deprecated password authentication):
```sh
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git pull
Username for 'https://github.com': phet-dev
Password for 'https://phet-dev@github.com': 
Already up-to-date.
```

It seemed like the credential helper wasn't saving the password, as it kept re-asking, so I set it up to store credentials:
```sh
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git config --global credential.helper cache
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git config --global credential.helper 'cache --timeout=36000000'
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git pull
Username for 'https://github.com': phet-dev
Password for 'https://phet-dev@github.com': 
Already up-to-date.
phet-admin@phet-server:/data/share/phet/phet-repos/interaction-dashboard$ git pull
Already up-to-date.
```

A final pull-all succeeded, then I deployed a new RC branch in the bumper repo which succeeded.

**Comment by mattpen** [comment]
I'm not sure why the PAT in the credentials doc wasn't working, it wasn't working for me on ox-dev either.  I checked and it is still working for rosetta, so I assume that it is wrong.  I created a new access token for use on ox-dev and it is working, we can use it when the cache times out next year.

**Comment by mattpen** [comment]
I think any remaining problems in this issue were solved when passwords stopped working for github in August. Closing.
