### ISSUE TITLE
How can perennial run from master, but check out prior versions during maintenance tasks?

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#235]
From https://github.com/phetsims/chipper/issues/1018, perennial needs the ability to check out prior versions while it runs.  We also want other sim code to be able to share code with perennial.  That led to the prior 2 solutions:

* (A) Copy paste select files from perennial to chipper, and keep perennial in master
* (B) Create another checkout of perennial (perennial-alias), and keep perennial in master

We discussed the second approach in today's dev meeting, and numerous complications and problems were revealed and discussed:
* perennial-alias isn't really a repo, but it is listed as one
* how do you update perennial-alias after making changes to perennial?
* the hassle of having 2 clones of one repo, and having to exclude one
* the hassle of npm update/prune in two perennials
* onboarding to explain why we have 2 clone of one repo, and how they should be treated differently.

This doesn't seem like a satisfactory solution, and I was wondering if we could find a better approach, so I would like to propose strategy (C):

* We add a trivial build step for perennial code (either webpack or cp), and run the built version.  That way it is free to check out different shas for perennial while it runs.
* The proposal does not require a second checkout, such as perennial-alias.  Everything is done through perennial.
* Perennial can depend on other repos, such as phet-core, and other repos (such as phetmarks or chipper) can depend on perennial.

This solves a lot of our old problems, at the cost of introducing the new problem:
* Making sure you build perennial from master before running it

Not all perennial tasks check out an older version of perennial.  Is there a way we can identify which tasks require a build, to minimize the hassle?  Also, I wonder if we were using a compiled language like Java, if we never would have had this problem in the first place if we already had to build perennial.

@jonathanolson can you please comment?

**Comment by mattpen** [comment]
As far as the build-server goes, I think we don't even need to go as far as introducing a build step.  We can have 2 clones without needing to worry about renaming them.  We have (a) `/data/share/phet/build-server/perennial` which is where we execute the build-server expressjs server and (b) `/data/share/phet/phet-repos/perennial` which is checked out in parallel with the other repos and is repo the build-server uses for running chipper commands (which depend on perennial (b)).  Perennial (b) is then free to live at any point in git history without worry about whether the build-server will run stale code, and perennial (a) can always be on master.

I'll leave comments pertaining to perennial's grunt commands for @jonathanolson.

**Comment by jonathanolson** [comment]
Some things to discuss:

1. Presumably we'd need to start every script with something that would build perennial? I don't want to manually be having to remember to build perennial all the time or else pulling all repos or common operations I use when starting work wouldn't work...https
2. I'm not convinced that "building" that way would work. The "built" code would still rely on node modules, so we're not compiling everything. Are we discussing compiling all the node modules into a built file also? Even if we had the correct node_modules at startup, I'm pretty sure dependencies access files AFTER startup. How I presume puppeteer works is that it loads node code on startup, but doesn't start Chromium until it's requested. So I presume if node_modules was wiped (because we'd check out an older version and npm update), then puppeteer wouldn't (e.g.) be able to launch chrome.js
3. Adds a lot of overhead on errors and debugging, if I'm having to work through a compiled object to get to errors in perennial.json

For reference, the entire point of perennial is "a place that's always on master" (thus the name), so if we would modify build code and scripts so that they would be versioned, presumably we'd want to move them to another (maybe new) repo for that purpose.

So I'm unconvinced this would be easier or possible. Either way, it would add a lot more effort to me than (a) the current method, or (b) having copies of a few files that we keep in sync manually.

**Comment by samreid** [comment]
> Presumably we'd need to start every script with something that would build perennial? 

Yes, or just remembering to build it when its codebase changes (from local changes or a pull).  This would have to be traded off against having to remember basically the same thing for perennial-alias.

> I'm not convinced that "building" that way would work. 

"building" could basically mean copy/pasting the directory.

> Adds a lot of overhead on errors and debugging, if I'm having to work through a compiled object to get to errors in perennial.json

If it is a copy/pasted directory, it would be easy enough to debug.

I'm seeing that perennial-alias is the copy/pasted directory, and does require extra maintenance.  But maybe it is acceptable for now?  I haven't heard about a lot of problems with perennial-alias.  Closing.
