### ISSUE TITLE
`grunt lint` in perennial seems to be missing errors

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#244]
If I add a lint error to perennial and run `grunt lint`, the following happens:

```
$ grunt lint
Running "lint" task
Running "lint" task

Done.


Done.
```

Whereas `grunt lint-everything`:
```
$ grunt lint-everything
Running "lint-everything" task

C:\Users\olson\phet\git\perennial\js\common\isGitRemoteDifferent.js
  31:1   error  'artasdrtart' is not defined  no-undef
  31:12  error  Missing semicolon             semi

✖ 2 problems (2 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Warning: 2 errors and 0 warnings Use --force to continue.

Aborted due to warnings.
```

However pre-commit hooks and IDEs seem to be properly linting.

@zepumph any thoughts on this?

**Comment by zepumph** [comment]
My first question is if `--eslint-disable-cache`

**Comment by zepumph** [comment]
With this patch:

Index: js/common/isGitRemoteDifferent.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/isGitRemoteDifferent.js b/js/common/isGitRemoteDifferent.js
--- a/js/common/isGitRemoteDifferent.js	(revision 7ebacc61adfaaab7724a8a4a70b4ed3f9a97dcf2)
+++ b/js/common/isGitRemoteDifferent.js	(date 1631550444119)
@@ -20,7 +20,7 @@
  * @returns {Promise.<boolean>}
  */
 module.exports = async function( repo ) {
-  assert( typeof repo === 'string' );
+  assert( typeof repo === "string" );
 
   const branch = await getBranch( repo );
   const currentSHA = await gitRevParse( repo, 'HEAD' );

```

the cache didn't change anything

```
 Michael ~/PhET/git/perennial (master)
 $ grunt lint
Running "lint" task
Running "lint" task

Done.


Done.

 Michael ~/PhET/git/perennial (master)
 $ grunt lint --disable-eslint-cache
Running "lint" task
Running "lint" task

Done.


Done.


```

**Comment by zepumph** [comment]
When I log the patterns passed to lint, it shows that it is linting chipper:

```js
=
  console.log( patterns, options );

```

```
 Michael ~/PhET/git/perennial (master)
 $ grunt lint --disable-eslint-cache
Running "lint" task
Running "lint" task
[ '../chipper' ] { cache: false, format: undefined, fix: undefined, warn: true }

Done.


Done.

```

**Comment by zepumph** [comment]
Looks like this broke during https://github.com/phetsims/perennial/commit/1647619ce05cc306e306166c8c5964b35a949cef, because we got rid of the repo option, but perennial's pattern wasn't specified directly. Fix coming in hot!

**Comment by zepumph** [comment]
A couple of fixes:

* make sure that if patterns is not provided, it is added on with a value to lint perennial.
* make sure that if the error from chipper occurs, it doesn't fail doubly (getting caught in chipper's and perennial's wrap task grunt failures, so I resolve errors in the execute command.



To test:

`grunt lint` -> lints perennial
`grunt lint --patterns=../perennial,../chipper` -> lints both repos
`grunt lint --patterns=../chipper` -> lints just chipper, not perennial


The only thing we COULD do, and I had implemented for a second before deleting, is to manually add perennial when the `patterns` option is provided by the user, but this seemed too clever, and not that helpful. @samreid, since you worked on https://github.com/phetsims/chipper/issues/1001, will you please review.

**Comment by samreid** [comment]
I reviewed the commits, and tested `grunt lint` in perennial with a bad lint.  Everything seems nice, thanks!  Closing.
