### ISSUE TITLE
Lint perennial

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#27]
I noticed a few places where there were lint errors, I don't think they should be there.

**Comment by zepumph** [comment]
@mattpen would you just quickly make sure that you think all is well. There was one that I did not do. build-server.js:159 erroring 'return outside of function' it seems like that could probably be replaced with process.exit() if we just wanted to quit, but I don't know enough to make that call for sure. (if that is the case line 175 and so on could probably be replaced as well.

**Comment by mattpen** [comment]
I'm not sure how to handle these errors:

```
106:1   error  Mismatched require statement values, fs!==fs.extra         require-statement-match
109:1   error  Mismatched require statement values, parseArgs!==minimist  require-statement-match
111:1   error  Mismatched require statement values, query!==pg-query      require-statement-match
```

fs.extra and pg-query are not allowable var names in javascript, so there is no way to satisfy these rules.  Should we add exceptions to the lint rules?

**Comment by zepumph** [comment]
Perhaps it is worth investigating updating the rule itself, but I've been adding this comment line to the end of each line:
`// eslint-disable-line require-statement-match` and it won't throw the error. I do that about 20 times in the installer builder because you have to require './module.js' as var module. If we change the rule we should make that exception too.

**Comment by zepumph** [comment]
Also im always curious about how to deal with code like the build server.js,   should we add use strict to every function or just put the whole file in an iffy?

**Comment by mattpen** [comment]
I'm not quite sure what the ramifications of putting the code in an iffy are.  @jbphet - do you have any opinions on this?

**Comment by jbphet** [comment]
I just did some poking around on the scope of `use strict`, and found a Stack Overflow article that said this about it:

> "use strict" applies only to function or program scope. So if you have fileA.js with "use strict" at the top, fileA.js executes in strict mode, and all functions defined in it will do the same when called.

From this, it sounds like having it at the top of the file should apply to all functions within that file.  @zepumph  - are you sure that it would even be necessary to enclose the code in an IIFE?

**Comment by zepumph** [comment]
Nice. I thought that use strict had to be in a function. Go for it!

**Comment by zepumph** [comment]
Actually I take it back. When you do this:

```js
'use strict';
(function(){
```

eslint gives an error saying: use the function form of 'use strict'

So unless you want to put that in every single function, I would surround it in an IIFE. Tell me if what i'm saying is different for you.

**Comment by mattpen** [comment]
This was actually already there, I recently removed it in https://github.com/phetsims/perennial/commit/5278089d72fe057597c5858b1d84e397b5b72dd5 due to the lint failure.  Maybe the lint rule should be modified?

**Comment by jbphet** [comment]
There is a directive that overrides the `env` value for eslint that can be placed at the top of a Node JS file and makes it unnecessary to wrap the contents of the file in an IIFE.  The directive is 'eslint-env node', and if I place the following lines towards the top of build-server.js, eslint behaves as desired:
```js
/* eslint-env node */
'use strict';
```
I had to update the version of eslint being used by my IDE, but once I did the `use strict` directive was no longer causing the `use the function form of 'use strict'` error, and the rest of the file had several issues that were correctly identified by eslint.  Using the command line approach for running, i.e. `grunt lint-all` from with a sim directory, caused the same issues to be identified.  In other words, it seems to be working well.

@zepumph pointed out that the directive is probably overriding the `env` setting that is currently defined in chipper\eslint\.eslintrc, which looks like this:
```json
  "env": {
    "browser": true
  },
```

@samreid joined the conversation, and expressed some concerns about **not** enclosing Node JS files in an IIFE, since we've done it for previous Node JS files and because he thought global variables may inadvertently be created.  We (mostly he) ran some tests, and we didn't see any signs of such global leakage.  My inclination at this point is not to require that the Node JS files be enclosed in an IIFE since it doesn't appear to be necessary.  If we decide to go with the approach of using this directive and not enclosing Node JS files in an IFFE, it might mean changing some existing files for consistency.  @samreid pointed out ChipperConstants.js as an example of such a file.

I'm adding @pixelzoom and @jonathanolson to the list of assignees to see if they have any input on whether to IIFE or not to IIFE.  There may be something that they know about Node JS scoping rules that can help with the decision.

I'm also marking for dev meeting, but we can remove this designation if we get this sorted out before the next dev meeting.

**Comment by samreid** [comment]
> We (mostly he) ran some tests, and we didn't see any signs of such global leakage.

To be clear, 

```js
x = 7; // not in an iife, declares a global named x, accessible in other files

(function(){
  z = 7; // node errors out
})();
```

However, we won't accidentally forget to put `var` because it is flagged as a lint error in both standard lint and env: node.

> My inclination at this point is not to require that the Node JS files be enclosed in an IIFE since it doesn't appear to be necessary.

It seems we should be using "env: node" since that is what it is intended for, but I'm curious what other linting rules are affected.

**Comment by pixelzoom** [comment]
Sorry - I don't have an input on IIFE vs non-IIFE, and have no experience with node scoping rules.

**Comment by jonathanolson** [comment]
Top StackOverflow (http://stackoverflow.com/questions/32463512/is-there-any-reason-to-define-module-exports-using-an-iife) says it doesn't matter. No preference.

**Comment by samreid** [comment]
@zepumph got volunteered to try to add `/* eslint-env node */` in all of our node files, and try linting and see how much trouble it would be to get their lint working.

**Comment by pixelzoom** [comment]
12/8/16 dev meeting:  Use `/* eslint-env node */` directive for node code. @zepumph will evaluate the effort required to remove IIFEs from existing node-specific code.  We'll revisit at next dev meeting.

**Comment by zepumph** [comment]
I'm going to close this an open a new issue to add that to all node files.
