### ISSUE TITLE
latest directory not being correctly identified

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#28]
There is a method in `build-server.js` called `getLocales` that is supposed to find the most recent directory, then find the file within that directory that contains the set of translated locales.  The code that attempts to identify the most recent directory is inadequate.  It looks like this:

```js
        var files = fs.readdirSync( simDirectory );
        var latest = files.sort()[ files.length - 1 ];
```

This suffers from several issues, not the least of which is that it will identify 1.1.9 as being the latest once 1.1.10 is published.  It also identifies non-directories as being directories.  This issue recently caused an issue with maintenance deployments.

This problem already cropped up in Rosetta (the translation utility), see https://github.com/phetsims/rosetta/issues/137, and we could use a similar solution.  This will result in some duplicated code across repositories, but at this point that is probably acceptable.

**Comment by jbphet** [comment]
This just bit us (I think) when @jonathanolson tried to do a redeploy of Molecules and Light, so I'm going to make this a top priority and get it fixed.

**Comment by jbphet** [comment]
This should now be fixed.  The deployment Molecules and Light of version 1.1.13 went awry in that it didn't produce any translations.  This was traced to the presence of a file of unknown origin in the sim's directory (the file was named `t2.txt`, and there was another one named `t1.txt`).  The algorithm to identify the latest deployment directory was intolerant to these files, and also used lexical ordering of the version directories.  I've added code that filters out directory/file names that don't match the PhET convention and also orders them correctly so that, for example, version `1.1.2` will be seen as an earlier release than `1.1.10`.  I tested this on Molecules and Light by copying the XML file containing the list of translations manually from the 1.1.12 directory to 1.1.13, then deploying version 1.1.14.  I actually had to do it twice because I forgot to use `--locales=*`, and the version of chipper on this branch is old enough that this was needed.  The deployment succeeded and appears to have built all translations.

I'm going to close this as fixed, and keep an eye out for any problems that could be related.

**Comment by jbphet** [comment]
I was just reflecting on this a bit, and I think I should have someone familiar with the phet-io deployment process review this change and make sure that it isn't going to mess anything up.  And, for that matter, just look over what I've done.  Reopening and assigning to @zepumph for this, he can reassign if appropriate, and can close if the code looks reasonable and doesn't negatively impact phet-io.

**Comment by zepumph** [comment]
I think that things will be good for now, because you are looking at versions that don't have "-rc" "-phetio" or 'dash something' after the version numbers. But if you want to extend this algorithm for those uses too ( like phetio), I think these lines would need to change a bit.
```js
  versions = versions.filter( function( path ) {
    var splitPath = path.split( '.' );
    if ( splitPath.length !== 3 ) {
      return false;
    }
    for ( var i = 0; i < 3; i++ ) {
      if ( isNaN( splitPath[ i ] ) ) {
        return false;
      }
    }
    return true;
  } );
```
changing the line to:
```js
// Take the first element after splitting on '-', handling the case "1.1.1-phetio"
      if ( isNaN( splitPath[ i ].split("-")[0] ) {
```


What do you think? It seems like it would still be backwards compatible to 'pure' versions without a dash. 

One other thought that we may want to think about (again perhaps this goes beyond the scope that is necessary) but take this version: `1.1.1-dev.4`. It would be filtered out. 

Perhaps none of these use cases fall into the realm that was designed for, but I thought I would express of few edge case concerns. Let me know if I can do anything. I really like the idea of generalizing this, and I think it will be helpful for phet-io deploys as well.

**Comment by jbphet** [comment]
Generalizing this eventually seems like a good idea, but there are enough questions about how this would be done and how it would be used that I don't think it's a high priority at the moment.  For instance, there is a proposal under consideration to modify the version numbering that would impact this (see https://github.com/phetsims/chipper/issues/560).  

The main thing that I'd like to be sure of - and that I'm asking for input on - is whether the update to the way in which the most recent directory is identified will have any impact on the building and publication of phet-io branded simulations.  I didn't work on adding the phet-io capability to the build server, which is why another pair of eyes is valuable.

@zepumph - can you confirm that this change won't negatively impact builds of phet-io?  If so, please comment in and close this issue.  If you feel strongly about generalizing the algorithm for finding the latest dir, please create a new issue and we can discuss there.  Thanks.

**Comment by zepumph** [comment]
I'm sorry if I wasn't being clear before. Yes I think there would be a problem. Here is a list of version numbers on phet-server for phetio sims:

```js
[mika5203@phet-server ~]$ cd /data/web/static/phet-io/sims/
[mika5203@phet-server sims]$ ls
arithmetic                       capacitor-lab-basics                      energy-skate-park-basics  graphing-lines         wave-on-a-string
balancing-act                    charges-and-fields                        expression-exchange       john-travoltage
balloons-and-static-electricity  circuit-construction-kit-black-box-study  faradays-law              molecules-and-light
beers-law-lab                    color-vision                              forces-and-motion-basics  proportion-playground
build-an-atom                    concentration                             function-builder          unit-rates
[mika5203@phet-server sims]$ cd capacitor-lab-basics/
[mika5203@phet-server capacitor-lab-basics]$ ls
 1.2.0-phetio  1.2.2-phetio  1.3.1-phetio  1.3.3-phetio  1.4.0-phetio  1.4.2-phetio
1.1.1-phetio    1.2.1-phetio  1.3.0-phetio  1.3.2-phetio  1.3.4-phetio  1.4.1-phetio
```


When you split on dots, you try to parse as int before splitting on the dash that holds the qualifier. I think that this is an important step because you are disregarding directories that have the phetio suffix. I would make the same suggestion as above to fix this.


Also another side note. `fs.existsSync` is deprecated and shouldn't probably be added to new code. I use  `fs.lstatSync( dir ).isDirectory()` instead. Here is some overflowing stack as a resource. http://stackoverflow.com/questions/28532820/fs-exists-fs-existssync-why-are-they-deprecated

**Comment by jonathanolson** [comment]
https://github.com/phetsims/perennial/issues/7 is a duplicate, some extra information there.

**Comment by jbphet** [comment]
I'm doing a bit of GitHub cleanup, and thought I'd follow up on this issue.  I just looked at the directories that exist on phet-server, and none of them have the -phetio name, and only very few have -rc in their name, and I think that may be a mistake (e.g. they are not supposed to be there).  That being the case, I'm not inclined to generalize this to handle the other cases suggested by @zepumph because I don't think it's needed here.  Assigning to @zepumph to implement the generalization if he would like to, close the issue, or make a case that I should do it.

**Comment by zepumph** [comment]
Things are going well. I don't see a need for the generalization!
