### ISSUE TITLE
generate-data reverted my-solar-system

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#282]
https://github.com/phetsims/perennial/commit/3be6e714dd5387dab19a52f143b10f614080134a happened, after my-solar-system was added to phet-io. @zepumph thoughts?

**Comment by zepumph** [comment]
Every so often I go onto the generate-data repos on bayes and find some repos with working copy changes. I haven't done this in about 2 years, and 8 repos had this. So I stashed the changes and pulled all. my-solar-system was one that couldn't be pulled.  What I found was that it was trying to find pre-commit-hooks in perennial still, which is why the commit failed and it still had working copy changes.

Thanks for the ping, and sorry about that. I updated things to always use the pre-commit hooks with steps in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#utilities-and-instrumentation-for-development-and-testing

Added back in https://github.com/phetsims/perennial/commit/e3e65507e10ee4d502bb6ab27faa8822cea55d9c today. 

Closing
