### ISSUE TITLE
New sim isn't showing alt screenshots on the website

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/perennial#314]
![image](https://user-images.githubusercontent.com/7852916/232142554-4df8d3a8-92b9-46ab-8f53-d94d631a8cde.png)

This was a sim that was previously a prototype, and is now published.

**Comment by mattpen** [comment]
This has been happening for a while apparently.  @arouinfar said in slack that "Screenshots are often wonky after publishing, I usually try the count alt images script and wait for the cache to clear".  This definitely should not be the case. I suspect that the build-server order of operations has a bug, it is probably build sim -> notify website -> build images which would cause the image counts during the project sync step to fail because the images aren't built yet.

**Comment by mattpen** [comment]
In the above commit I fixed the problem with the order of operations.  @chrisklus and I tested this on ox-dev and got a positive result.  I currently don't have a reliable way to test for a negative result or a way to confirm that this was not a false positive result because the bug relied on race conditions to be present.  But I feel confident that at a minimum this has not made things worse and is likely to have fied the problem.

**Comment by mattpen** [comment]
@zepumph agreed to do a quick review of the change tomorrow.

**Comment by zepumph** [comment]
@mattpen and I talked, and I had just a few minor improvements. Otherwise this looks like a nice change. Thanks!

**Comment by mattpen** [comment]
I added some improvements and deployed the fix to production.
