### ISSUE TITLE
Should package.json contain "grunt-eslint"?

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#35]
In https://github.com/phetsims/chipper/issues/565 we stopped using "grunt-eslint" and removed it from all package.json (including perennial's).  However, I'm unsure how perennial works and whether that grunt-eslint entry may be necessary for building maintenance versions.  I suspect not, because the sim will have the grunt-eslint entry but I'm just not 100% sure.  Assigned to some people that I saw on recent commits in perennial.

**Comment by zepumph** [comment]
I'm not really sure about perennial. Sorry I will have to defer to more capable opinions here.

**Comment by jonathanolson** [comment]
Presumably it shouldn't need the old eslint version, and can be removed.

**Comment by jbphet** [comment]
I also think it would be safe to remove it.  We can plan to do it, pull on phet-server, then do a test build of a sim (e.g. chains) as a test if you like.

**Comment by samreid** [comment]
Sounds good @jbphet, I have already removed it.  Can you take the next steps, or should someone else?

**Comment by jbphet** [comment]
I'll test.

**Comment by jbphet** [comment]
I'd forgotten about this, but the build server pulls perennial each time a build request occurs, so this change was automatically propagated to the server on the first build after the change was committed.  From checking the file update time on phet-server, the modified `package.json` file has been in use since 11:06 AM on April 17th, which is roughly half an hour after the commit was made (see https://github.com/phetsims/perennial/commit/f7f42e3d60b18f00fe950c3647d5d69d383d080b).  I looked through the build server log, and there have been 16 successful builds since this time, and I'm not seeing any failures.  While this is probably not the ideal way to test changes like this, I think we can safely conclude that it didn't break the build process, at least not in any major way.  There is still a chance that some really old simulation branch will have a problem, but I think the risk of this is low.  I'm going to go ahead and close this issue, but am tagging @samreid to reopen if he disagrees.

**Comment by samreid** [comment]
It sounds like things are working ok, but it sounds like we need to be careful what we commit to perennial.
