### ISSUE TITLE
How/Should perennial be able to use code from phet-core, like IntentionalAny?

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#371]
How/Should perennial be able to use code from phet-core, like IntentionalAny? Keep in mind we do not want to create phet-core-alias.

**Comment by samreid** [comment]
I am reluctant to move more code to perennial while we have this problem: https://github.com/phetsims/perennial/issues/363

**Comment by samreid** [comment]
@jonathanolson @zepumph and I met today to discuss https://github.com/phetsims/perennial/issues/363 and agreed that https://github.com/phetsims/perennial/issues/401 would be good to investigate. 

We do not want to move phet-core code such as `optionize` or `IntentionalAny` to perennial. Instead, we would prefer that perennial can depend on phet-core. In order to do so without creating phet-core-alias, we will investigate the above approaches.

Until then, perennial should use `any` instead of `IntentionalAny` and `assignIn` or other alternatives to `optionize`.

**Comment by zepumph** [comment]
We cannot justify changes to our pattern for perennial-alias over in https://github.com/phetsims/perennial/issues/363.

Given that, here are solutions we don't want to do:
* phet-core-alias: This won't even work, because you need a different string in the import depending on if it is perennial or perennial-alias. This could work if they were dynamic imports, but seriously. Ew.
* Copy/move all files we want from phet-core over to perennial. Gross!
* Publish an npm module of phet-core so that perennial can use pinned version of it as it changes. No way bronco. 

And so, @samreid and I regret to inform you, reader, that it is time to close this issue. We will continue with perennial unable to use phet-core or anything else as a dependency. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
I'm glad this issue reopened, thanks @phet-dev. I was working on https://github.com/phetsims/perennial/issues/404 and it was feeling unfortunate that perennial cannot call code in chipper. I believe if we can demarcate sha operations in https://github.com/phetsims/perennial/issues/402 then we can allow our non-sha operation code to depend on chipper and phet-core, etc. So I'd like to take a look.

**Comment by samreid** [comment]
@zepumph and I agreed with https://github.com/phetsims/perennial/issues/371#issuecomment-2486780422
