### ISSUE TITLE
Support typescript with pm2

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#381]
From https://github.com/phetsims/chipper/issues/1481, https://pm2.io/docs/runtime/integration/transpilers/#typescript%5C describes how we can launch typescript scripts via pm2.

Until we upgrade, these entry points and their dependencies are stuck as *.js.
https://github.com/phetsims/aqua/blob/988b2f784fff708ba525d0e61ca183b286e3d6a5/js/config/bayes.pm2.config.js#L21-L38

**Comment by zepumph** [comment]
I'm hitting this in https://github.com/phetsims/aqua/issues/219. It is very easy to support this with `sage run` with this:

```
args: 'run . . .',
script: '../perennial/bin/sage',
interpreter: '/bin/bash',
```

The issue is that this only runs well in fork mode, it won't work for our clustered code, like ct-puppeteer-client. I learned about this here: 

https://stackoverflow.com/questions/34682035/cluster-and-fork-mode-difference-in-pm2.

I'll keep investigating.

**Comment by zepumph** [comment]
From this I believe that to support cluster mode, we will be required to transpile the typescript into javascript before supporting cluster mode.

**Comment by zepumph** [comment]
I believe this is relatively close. I restarted all bayes processes to run with `sage run`, and it is working well!

**Comment by zepumph** [comment]
Yes. I believe this is ready to close! Sparky and Bayes are both running tasks with sage run with a bash interpreter.
