### ISSUE TITLE
Isolate perennial behaviors and entry points that operate on SHAs

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#402]
The main distinguishing characteristic of perennial is that it can operate on SHAs of perennial-alias. It seems important to demarcate the subset of perennial functionality that is about SHA operations. Perhaps a dedicated directory in perennial. We should make an effort to minimize tasks that forward from chipper to perennial, limiting it to the ones that perform SHA operations.  It has been very confusing lately to be working in perennial and perennial-alias and not knowing which in getting invoked when, and after pushing a change having to pull the opposite repo right away to keep in sync.

**Comment by zepumph** [comment]
In https://github.com/phetsims/perennial/issues/401 we found that there are no easy ways of getting around perennial checking out our codebase, and furthermore, most of what we would want to separate in this issue is just as likely to be generalized to apply to either the main codebase (sibling) AND separate checkouts in `release-branches/` (like `gitPush` or something). So we likely won't work on this again. Closing for now.
