### ISSUE TITLE
provide support for restoring working copy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#58]
There have been too many times when I've run pull-all.sh, only to discover that master is broken. While it's good to discover that master is broken, it's often inconvenient, causes me to change my workplan for the day, and slows my progress on sim development.  It would be nice to have a convenient way to (a) create a log file of _all_ shas in my working copy, so that I have a set of "safe" shas", and (b) restore shas from such a log file.  

Proposal:

• Provide a grunt task to write working-copy shas to a log file. E.g. `grunt save-shas filename`. 

• Provide a grunt task to restore shas from a log file.  E.g. `grunt restore-shas filename`.

• Modify pull-all.sh so that it runs `grunt save-shas $HOME/.phet/shas.log` before it updates the working copy. 

Using dependencies.json format and existing tasks would likely provide leverage for implementing this.

**Comment by pixelzoom** [comment]
status.sh can be used to create a log file, for example:

`print-shas.sh | grep -v Missing > log`

(The `grep -v` is a workaround for https://github.com/phetsims/perennial/issues/59.)

**Comment by pixelzoom** [comment]
Something like this (untested) would work for `restore-shas.sh`.   I have not checked this into perennial master because of the on-going chipper 2.0 work.

```
#!/bin/bash
#====================================================================================================
#
# Restores shas from a log file that was created using print-shas.sh
#
# Usage:
# % print-shas.sh > log
# % restore-shas.sh log
#
# Author: Chris Malley (PixelZoom, Inc.)
#
#====================================================================================================

PERENNIAL_BIN=`dirname "${BASH_SOURCE[0]}"`
PERENNIAL_DIR=${PERENNIAL_BIN}/..
cd ${PERENNIAL_DIR}

# verify number of command line args
if [ $# != 1 ]; then
  echo "usage: restore-shas.sh logfile"
  exit 1
fi

# verify that logfile exists
LOGFILE=$1
if [ ! -f ${LOGFILE} ]; then
    echo "log file does not exist: ${LOGFILE}"
    exit 1
fi

cat ${LOGFILE} | while read -r line; do
  REPO=`echo $line |cut -d' ' -f1`
  SHA=`echo $line |cut -d' ' -f3`
  cd ../${REPO}
  git checkout ${SHA}
done
```

**Comment by samreid** [comment]
I can see value in a utility like this, here are some recommendations:

1. Consider keeping a record of N previous logfiles (N>1), otherwise if a developer accidentally runs `pull-all.sh` twice in a row, they will lose their good SHAs.
2. Consider implementing this using dependencies.json/checkout-shas/etc since we already need to support most of this functionality, and it will run steps like npm update, etc.
3. (Just brainstorming on this one): would it be helpful for `pull-all.sh` to automatically check on Bayes and let you know if you are getting buggy SHAs before you even check them out?
4. Another possibility: keep track of the SHA sets on Bayes.  So if you need to revert to prior shas, you could look at Bayes, look back for the most recent green "tests passing" column, then copy paste SHAs from that column for checkout.  This possibility will only work if Bayes doesn't need to be restarted too much (since that clears the history)--or we can make bayes tests persistent across restarts.

**Comment by samreid** [comment]
The other "pre-emptive" solution is to require pre-commit (or pre-push) tests.  This could slow down some kinds of workflow, but could prevent the kind of problem @pixelzoom identified.  If we go down this path, we would want the following features:
1. Commits (or pushes) on a repo could require testing to pass on the repo and all downstream repos that depend on the repo. The main point is to speed up the testing--only testing the minimum necessary set.
2. We would want to be able to run the continuous testing server (that currently runs on Bayes) on any computer.  
3. We may also want to edit it so that it runs the tests based on the working copy, not a fixed snapshot checkout of stable shas.
4. Would we need a way to intentionally commit/push code that is failing testing (say, for sharing code to work on?)
5. Could/should we make this strategy apply to Bayes only?
6. How can we automate it so that it happens automatically as a pre-commit/pre-push step?

**Comment by pixelzoom** [comment]
Regardless of whether we pursue one of the more complicated solutions proposed in https://github.com/phetsims/perennial/issues/58#issuecomment-353271728 and https://github.com/phetsims/perennial/issues/58#issuecomment-353389913, I'd like to proceed with fixing print-shas.sh (see #59) and committing `restore-shas.sh`.  This will address 95% of what I need, with 1% of the work compared to other options.  

@jonathanolson if I add `restore-shas.sh`, which branches (in addition to master) should I add it to?

**Comment by pixelzoom** [comment]
Here's the usage after I make the minimal number of changes:

```
% print-shas.sh > log
% pull-all.sh
// arg! things are broken!
 %restore-shas.sh log
// whew, back to where I was.
```

**Comment by pixelzoom** [comment]
The above usage requires you to remember to run `print-shas.sh` before doing `pull-all.sh`.  For 15 minutes more work, I could make `pull-all` run `print-shas.sh > $HOME/.phet/print-shas.log`, and `restore-shas.sh` use  `$HOME/.phet/print-shas.log` by default. Then the usage would be:

```
% pull-all.sh
// arg! things are broken!
% restore-shas.sh
// whew, back to where I was.
```

**Comment by samreid** [comment]
I think it's worth the 15 minutes.

**Comment by pixelzoom** [comment]
12/21/17 dev meeting:

OK to proceed with proposal in https://github.com/phetsims/perennial/issues/58#issuecomment-353412428.

@jonathanolson would like to have something that reverts everything to a specified date.

**Comment by pixelzoom** [comment]
pull-all.sh now calls `print-shas.sh > $HOME/.phet/print-shas.log`.  If $HOME/.phet/ doesn't exist, it is created.

**Comment by pixelzoom** [comment]
`restore-shas.sh` is pushed and appears to be working.   The only issue is that it will put all repos in your working copy in a detached HEAD state.  So before you do another `pull-all.sh`, you'll need to run `for-each.sh active-repos git checkout master`.  Wondering if I should be using something other than `git checkout ${SHA}` in `restore-shas.sh`?

**Comment by pixelzoom** [comment]
@jonathanolson @samreid advice on https://github.com/phetsims/perennial/issues/58#issuecomment-353454549?

**Comment by jonathanolson** [comment]
> So before you do another pull-all.sh, you'll need to run for-each.sh active-repos git checkout master

`grunt checkout-master-all` in perennial is helpful for doing the equivalent.

> Wondering if I should be using something other than git checkout ${SHA} in restore-shas.sh?

I think that's just the cost of checking out older things. Adding logic that tries to keep unchanged things on master doesn't seem too helpful, as it would be inconsistent (you'll still have some things on detached heads). You'll presumably need to re-check-out master on what you want to change/commit to, hopefully the breaking changes didn't affect that repo.

> And what happens if some repos were on non-master when pull-all.sh was run?

Seems fine to record the SHAs and pull with whatever branch it is on. Not sure what happens when you pull a detached head, but it should continue on to other repositories.

So in general it seems like a necessary inconvenience if you have to switch to older SHAs.

**Comment by samreid** [comment]
How about `cp -r ~/git-root ~./git-root-backup` then `pull-all.sh`.  To revert, you `mv ~/git-root` to `git-root-old` and `mv ~/.git-root-backup` to `~/.git-root`.  Then you are still in the desired branches.  Or will this tear up our SSDs?

**Comment by samreid** [comment]
There appears to be a much better solution thanks to https://stackoverflow.com/questions/1223354/undo-git-pull-how-to-bring-repos-to-old-state

```
for-each.sh active-repos git reset --hard master@{"10 minutes ago"}
```

PROS: This should alleviate the need for complex scripts such as https://github.com/phetsims/perennial/issues/58#issuecomment-353184433 and will be tolerant to multiple pulls.  No need to keep track of a log file.
CONS: There are undoubtedly drawbacks of this approach but I haven't tested it yet and am hence unaware of them.  I'm not sure if you end up in fixed SHAs or not.

**Comment by samreid** [comment]
UPDATE: I tried running `git reset --hard master@{"10 minutes ago"}` in a sim repo and it did not report that I was in detached head.

**Comment by pixelzoom** [comment]
@samreid said:
> PROS: This should alleviate the need for complex scripts such as #58 (comment) 

You consider that complex?...

Getting a set of shas and getting all repos based on time are apples and oranges.  Getting based on time _will not_ get you back to where you were before a pull-all.sh.   You are highly likely to pick up additional changes that had been pushed but were not in your working copy. 

`restore-shas.sh` is working fine for me now, and I'm willing to live with detached HEADs in the interim.  So I'm going to consider this issue closed.  If anyone wants to create an issue for a more robust solution, go for it.

**Comment by pixelzoom** [comment]
Mentioning @jbphet site he was out when we discussed adding `restore-shas.sh`.  Let me know if you have any questions.  Summary: Before pulling anything, `pull-all.sh` automatically writes `$HOME/.phet/print-shas.out`.  If you discover that what you pulled is broken, you can run `restore-shas.sh` to restore the shas from `$HOME/.phet/print-shas.out`.  After running `restore-shas.sh`, all of your repos will have a detached HEAD.
