### ISSUE TITLE
Investigate issue with add html translator

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#72]
```
Jan 16 13:51:49 phet-server.int.colorado.edu build-server[13162]: info: URL for adding translator to credits = https://phet.colorado.edu/services/add-html-translator?simName=async function () {
Jan 16 13:51:49 phet-server.int.colorado.edu build-server[13162]: await execWithAbort( 'grunt', [ 'checkout-master-all' ], constants.PERENNIAL );
Jan 16 13:51:49 phet-server.int.colorado.edu build-server[13162]: await execWithAbort( 'rm', [ '-rf', buildDir ], '.' );
Jan 16 13:51:49 phet-server.int.colorado.edu build-server[13162]: Promise.resolve();
Jan 16 13:51:49 phet-server.int.colorado.edu build-server[13162]: }&locale=ab&userId=undefined&authorizationCode=b3c6fe815010faa77433430b81ad2892

```

**Comment by mattpen** [comment]
This should have been fixed in the above commit.  It has been deployed and is ready for a test.

**Comment by jbphet** [comment]
This does not appear to be fixed.  We have started to receive emails from translators that the translations are not being published.  The following translations have been submitted recently, appear to succeed in rosetta, and are not appearing on the site (some sim+locale combinations appear multiple times because the translator retried):

| Build Time | Sim | Locale  |
| ------------- | ------------- | ----- |
|  Feb 13 2018 06:58:47 MST | capacitor-lab-basics | be (Belarusian) |
|  Feb 12 2018 23:30:51 MST | pendulum-lab | hi (Hindi) |
|  Feb 12 2018 23:10:25 MST | pendulum-lab | hi (Hindi) |
|  Feb 10 2018 23:03:21 MST | capacitor-lab-basics | be (Belarusian) |
| Feb 09 2018 19:50:28 MST | atomic-interactions | hr (Croatian) |

**Comment by jbphet** [comment]
Also, when @mattpen and I looked at this yesterday, he said that there wasn't a good way to push a translation to the site if the automated process doesn't work.  This seems like a problem to me.  Yesterday, we asked the translator for one of the failures above to retry the submission, which they did, and it still didn't work, so we are in the awkward position of enlisting translators to do our testing.  So, as part of this effort, I believe that we should implement a means of manually pushing completed translations to the website if the automated process fails.

**Comment by mattpen** [comment]
I've been taking a look at the failed CLB in be tranlsation at 6:58 today.

The addTranslator is now sending the correct parameters, but the call appears to have failed on the website side because a LocalizedSimulation object for `be` did not exists.  This is created by the synchronize project call.  The build-server logs report that the call was successful, but the logs on the website side omit the `be` locale, leading me to believe that there is an asynchronous problem, or somehow things are occurring in the wrong order.  The build-server should first update the sim-name.xml file with the new locale from rosetta, then make the sync project call after that file has been rewritten.  However, it does not look like this is happening, so that's where I will look next.

**Comment by mattpen** [comment]
Looks like we were missing `await` on the write file call in the build-server.

**Comment by mattpen** [comment]
@jbphet - I was able to retrigger each of the translations in the list above.  CLB/be, PL/hi, and AI/hr are all available on the website and the translation credits have all been added.

The root cause of this problem was that the synchronize project process on the website and the writing of the new sim-name.xml file were happening asynchronously, so when new locales were translated for a sim, they were not actually added to the website until the sim was translated twice.  This should now be happening synchronously and there is logging in place to verify that.  I tested this with chains on ox-dev and it appears to be working correctly.

>I believe that we should implement a means of manually pushing completed translations to the website if the automated process fails.

I have found a means to run the synchronize project and add translator calls after the fact.  Do we need an end-to-end means of recreating an entire transaction from rosetta?  I'm not sure how we would test this as currently you need to be logged into the website as a user in order to test the entire process.

**Comment by jbphet** [comment]
I just checked the web site, and am seeing the translations, so this looks good - thanks @mattpen.  I'll watch the translation log over the next few days to make sure all is well.

> Do we need an end-to-end means of recreating an entire transaction from rosetta?

I don't think so - I just wanted to be sure that we could publish translations that end up in this state since there were a few, and since it seems possible that an issue like this could recur.  It sounds like you've figured something out for that, so we should be good to go.  Having said that, if you were out, would anyone else be able to do this if needed?

**Comment by jbphet** [comment]
@oliver-phet - you mentioned to me that we'd gotten some emails from translators about this problem.  Can you look through the table in https://github.com/phetsims/perennial/issues/72#issuecomment-365352169 and see if this matches up with who you have heard from, and let them know that their translations are now live and the issue should be resolved?  Also, they should let us know if they see any more anomalies.

**Comment by jbphet** [comment]
We received two new translations early this morning.  The locale for both is "nn", which is Norwegian Nynorsk, and the sims were build-an-atom and pendulum-lab.  Both are visible on the web site as of this writing.  This seems to indicate that the problem with sims getting published is resolved, so I'm going to close this issue.  I'll keep an eye on translations and re-open if I see any publication problems.
