### ISSUE TITLE
Add a check for VPN

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#98]
I've had deployments fail several times because VPN wasn't running, I'm going to add a prompt.

**Comment by samreid** [comment]
Added in the preceding commit, @jonathanolson am I doing this right?

**Comment by samreid** [comment]
Also, do we need this for `grunt rc` or `grunt prod`?

**Comment by jonathanolson** [comment]
I think there's an issue for (a) doing a network check first before other things, so it doesn't require a prompt, and (b) doing it for all deployments.

**Comment by samreid** [comment]
That sounds nice.  I didn't see a perennial issue referring to VPN (other than this one), I'm not sure where to look.  Perhaps we can leave this in place until that other issue is complete?  I'm not the only one who will benefit from this--another developer ran into this last week.

**Comment by samreid** [comment]
Sorry, wrong commit.  It belonged over in https://github.com/phetsims/wave-interference/issues/42

**Comment by jonathanolson** [comment]
I've added a check, but weirdly accesses without VPN (right now on this computer) to bayes are timing out rather than failing to immediately connect.

I don't want to add `-o ConnectTimeout=10` to SSH options, since that isn't portable. @samreid can you check how this behaves (trying to dev deploy) on your end?

**Comment by jonathanolson** [comment]
@samreid noted in Slack that that this was working. Closing.
